// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wabfgujvjmlwfmogpopr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYmZndWp2am1sd2Ztb2dwb3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDI4MjcsImV4cCI6MjA2MDQxODgyN30.T2VN7ukUK2JRUab5b8YBRxwVM7V80RO0HvxOdUD_YoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);